### ISSUE TITLE
What and where is ninja?

### ISSUE THREAD

**Issue by The-SamminAter** [DragonBuild/Installer#5]
For (and on) iOS, where can one obtain ninja, and what is it? A quick search in Cydia/Zebra yields no results.

**Comment by DimitarNestorov** [comment]
DragonBuild now has an official repo (https://repo.krit.me) where you can install it from. Can you try installing it from there?

https://twitter.com/_dragonbuild/status/1312895012372348928?s=20:
> It should work out of the box after installation.
> 
> ‘dragon test’ to run the test suite (statusviz will probably fail)
